
(function(){
'use strict';
const TYPES=['flower','coffee','box','heart','leaf','blue'];
const TYPE_NAMES={flower:'Flowers',coffee:'Coffee Cups',box:'Treat Boxes',heart:'Love Hearts',leaf:'Garden Leaves',blue:'Blue Gems'};
const LEVELS=[
  {moves:28,goals:['flower','coffee','box'],needs:[14,8,8],lesson:'Match three pieces to help Coco tidy the cafe garden.'},
  {moves:27,goals:['coffee','heart','leaf'],needs:[12,12,10],lesson:'Match four pieces to make a rocket.'},
  {moves:26,goals:['box','blue','flower'],needs:[14,14,12],lesson:'Match five pieces to make a rainbow treat.'},
  {moves:25,goals:['leaf','coffee','heart'],needs:[16,14,14],lesson:'Use bombs for big messy patches.'},
  {moves:24,goals:['blue','box','flower'],needs:[18,16,16],lesson:'Combine cascades and boosters for bigger rewards.'}
];
const ROOM_TASKS=[
  {key:'sofa',label:'Add the cosy pink sofa',reward:'Coco has a proper nap spot now.'},
  {key:'table',label:'Set up the coffee table',reward:'Shel has somewhere cute for her latte.'},
  {key:'plant',label:'Add garden plants',reward:'The room feels fresh and pretty.'},
  {key:'curtain',label:'Hang warm curtains',reward:'The cafe corner looks finished.'}
];
const $=s=>document.querySelector(s); const $$=s=>Array.from(document.querySelectorAll(s));
const state={level:1,coins:12450,stars:45,lives:5,sound:true,vibe:true,inbox:false,tutorial:{intro:false,boost:false,power:false,room:false},room:{sofa:false,table:false,plant:false,curtain:false}};
try{Object.assign(state,JSON.parse(localStorage.cocoGardenSave||'{}')); state.tutorial=Object.assign({intro:false,boost:false,power:false,room:false},state.tutorial||{}); state.room=Object.assign({sofa:false,table:false,plant:false,curtain:false},state.room||{})}catch(e){}
let board=[],moves=26,score=0,selected=null,down=null,busy=false,screen='home',goals=[],audio=null,levelConfig=null,cascadeDepth=0;
let boosters={rocket:5,bomb:4,rainbow:2,moves:3};
function save(){localStorage.cocoGardenSave=JSON.stringify(state)}
function ctx(){try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)(); if(audio.state==='suspended')audio.resume(); return audio}catch(e){return null}}
function tone(f=520,d=.08,type='triangle',gain=.055){try{if(!state.sound)return; const c=ctx(); if(!c||c.state!=='running')return; const o=c.createOscillator(),g=c.createGain(); o.type=type; o.frequency.value=f; g.gain.value=.001; o.connect(g); g.connect(c.destination); o.start(); g.gain.linearRampToValueAtTime(gain,c.currentTime+.012); g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+d); o.stop(c.currentTime+d+.03)}catch(e){}}
function melody(){tone(523,.1); setTimeout(()=>tone(659,.1),90); setTimeout(()=>tone(784,.14),180)}
function fanfare(){melody(); setTimeout(()=>tone(1046,.16,'triangle',.05),300); setTimeout(()=>tone(1318,.20,'triangle',.045),470)}
function buzz(n=25){try{if(state.vibe&&navigator.vibrate)navigator.vibrate(n)}catch(e){}}
function levelFor(){const base=LEVELS[(Math.max(1,state.level)-1)%LEVELS.length]; const cycle=Math.floor((Math.max(1,state.level)-1)/LEVELS.length); return {moves:Math.max(20,base.moves-cycle),goals:base.goals.slice(),needs:base.needs.map(n=>n+cycle*3),lesson:base.lesson}}
function mapGoalHtml(cfg=levelFor()){return cfg.goals.map((t,i)=>`<div class="mapGoal"><span class="goalIcon ${t}"><i></i></span><b>${cfg.needs[i]}</b></div>`).join('')}
function sync(){ $$('.coins').forEach(e=>e.textContent=Number(state.coins).toLocaleString()); $$('.stars').forEach(e=>e.textContent=state.stars); $$('.levelNum').forEach(e=>e.textContent=state.level); const lb=$('#levelButton'); if(lb)lb.textContent='Level '+state.level; const ib=$('#inboxBadge'); if(ib)ib.style.display=state.inbox?'none':'grid'; $$('[data-boost]').forEach(b=>{const n=b.dataset.boost,c=b.querySelector('.count'); if(c&&boosters[n]!=null)c.textContent=boosters[n]; b.classList.toggle('zero',boosters[n]===0)}); const mg=$('.mapGoals'); if(mg)mg.innerHTML=mapGoalHtml(); renderRoom(); }
function show(id){screen=id; $$('.screen').forEach(s=>s.classList.toggle('active',s.id===id)); if(id==='game'&&!board.length)newLevel(); if(id==='makeover')setTimeout(()=>coachRoom(),250); sync(); setTimeout(render,40); tone(430,.045)}
function rand(){return TYPES[Math.floor(Math.random()*TYPES.length)]}
function fill(){board=[]; for(let y=0;y<8;y++){board[y]=[]; for(let x=0;x<8;x++){let t; do{t=rand()}while((x>1&&board[y][x-1].type===t&&board[y][x-2].type===t)||(y>1&&board[y-1][x].type===t&&board[y-2][x].type===t)); board[y][x]={type:t,special:null,dir:Math.random()<.5?'row':'col',new:true}}}}
function seedGoodMove(){board[6][1]={type:'flower',special:null,dir:'row',new:true};board[6][2]={type:'flower',special:null,dir:'row',new:true};board[6][4]={type:'flower',special:null,dir:'row',new:true};board[7][3]={type:'flower',special:null,dir:'row',new:true}}
function newLevel(){levelConfig=levelFor(); moves=levelConfig.moves;score=0;selected=null;down=null;busy=false;cascadeDepth=0;goals=levelConfig.goals.map((t,i)=>({id:t,type:t,need:levelConfig.needs[i],got:0,name:TYPE_NAMES[t]}));fill();seedGoodMove();renderGoals();updateGame();render();setTimeout(()=>{hint(levelConfig.lesson); if(!state.tutorial.intro)coachIntro()},350)}
function renderGoals(){const el=$('#goalRows'); if(!el)return; el.innerHTML=goals.map(g=>`<div class="goalRow"><span class="goalIcon ${g.id}"><i></i></span><span>${g.name}</span><b id="goal_${g.id}">${g.got}/${g.need}</b></div>`).join('')}
function updateGame(){const m=$('#moves'),s=$('#score'),f=$('#starFill'); if(m)m.textContent=moves; if(s)s.textContent=score.toLocaleString(); if(f)f.style.width=Math.min(100,score/(1500+state.level*150)*100)+'%'; goals.forEach(g=>{const e=$('#goal_'+g.id); if(e)e.textContent=g.got+'/'+g.need}); sync()}
function pc(p){return p.special==='rocket'?'specialRocket':p.special==='bomb'?'specialBomb':p.special==='rainbow'?'specialRainbow':p.type}
function render(){const el=$('#board'); if(!el||!board.length)return; let html=''; for(let y=0;y<8;y++)for(let x=0;x<8;x++){const p=board[y][x]; const sel=selected&&selected.x===x&&selected.y===y?' selected':''; html+=`<button class="cell ${((x+y)%2)?'alt':''}${sel}${p.new?' new':''}" data-x="${x}" data-y="${y}" aria-label="${p.special?p.special+' ':''}${TYPE_NAMES[p.type]}"><span class="piece ${pc(p)}"><i></i></span></button>`; p.new=false;} el.innerHTML=html;}
function cellAt(px,py){const el=$('#board'); if(!el)return null; const r=el.getBoundingClientRect(); if(!r.width||!r.height)return null; const x=Math.floor((px-r.left)/(r.width/8)), y=Math.floor((py-r.top)/(r.height/8)); return x>=0&&x<8&&y>=0&&y<8?{x,y}:null}
function adjacent(a,b){return a&&b&&Math.abs(a.x-b.x)+Math.abs(a.y-b.y)===1}
function swap(a,b){const t=board[a.y][a.x]; board[a.y][a.x]=board[b.y][b.x]; board[b.y][b.x]=t}
function getGroups(){const out=[]; for(let y=0;y<8;y++){let r=[{x:0,y}]; for(let x=1;x<8;x++){if(board[y][x].type===board[y][x-1].type)r.push({x,y}); else{if(r.length>=3)out.push(r.slice()); r=[{x,y}]}} if(r.length>=3)out.push(r.slice())} for(let x=0;x<8;x++){let r=[{x,y:0}]; for(let y=1;y<8;y++){if(board[y][x].type===board[y-1][x].type)r.push({x,y}); else{if(r.length>=3)out.push(r.slice()); r=[{x,y}]}} if(r.length>=3)out.push(r.slice())} return out}
function unique(gs){const seen=new Set(),out=[]; gs.flat().forEach(c=>{const k=c.x+','+c.y; if(!seen.has(k)){seen.add(k); out.push(c)}}); return out}
function specialFrom(gs,origin){let best=null; gs.forEach(g=>{if(g.length>=4&&(!best||g.length>best.length))best=g}); if(!best&&gs.length>1)best=gs[0]; if(!best)return null; const spot=best.find(c=>origin&&c.x===origin.x&&c.y===origin.y)||best[Math.floor(best.length/2)]; const type=best.length>=5?'rainbow':(gs.length>1?'bomb':'rocket'); return {x:spot.x,y:spot.y,type,dir:(best[0].y===best[best.length-1].y?'row':'col')};}
function attemptSwap(a,b){if(busy||!adjacent(a,b))return; busy=true; const pa=board[a.y][a.x],pb=board[b.y][b.x]; if(pa.special){moves=Math.max(0,moves-1);activate(a,pb.type,'Power!');return} if(pb.special){moves=Math.max(0,moves-1);activate(b,pa.type,'Power!');return} swap(a,b); render(); setTimeout(()=>{const gs=getGroups(); if(!gs.length){swap(a,b); busy=false; selected=null; render(); tone(145,.08,'sawtooth'); hint('No match. Try another swap.'); return} moves=Math.max(0,moves-1); resolve(gs,{label:gs.length>1?'Combo!':'Great!',special:specialFrom(gs,b)})},110)}
function collect(cells){cells.forEach(c=>{const p=board[c.y]?.[c.x]; if(!p)return; goals.forEach(g=>{if(p.type===g.type&&g.got<g.need)g.got++})})}
function resolve(gs,opt={}){busy=true; cascadeDepth++; const cells=unique(gs); const keep=opt.special; const clear=cells.filter(c=>!keep||c.x!==keep.x||c.y!==keep.y); score+=cells.length*(130+cascadeDepth*25); collect(cells); pop(clear); particles(clear); if(cells.length>=5)shockwave(); toast(opt.label||'Nice!'); buzz(30); tone(720+cascadeDepth*35,.09); setTimeout(()=>{clear.forEach(c=>{board[c.y][c.x]=null}); if(keep&&board[keep.y]?.[keep.x]){board[keep.y][keep.x].special=keep.type; board[keep.y][keep.x].dir=keep.dir; toast(keep.type==='rainbow'?'RAINBOW!':keep.type==='bomb'?'BOMB!':'ROCKET!'); if(!state.tutorial.power){state.tutorial.power=true; save(); setTimeout(()=>coachPower(keep.type),500)}} drop(); render(); updateGame(); setTimeout(()=>{const more=getGroups(); if(more.length)resolve(more,{label:cascadeDepth>1?'Mega Combo!':'Wow Combo!'}); else{busy=false; cascadeDepth=0; checkEnd(); render()}},300)},330)}
function pop(cells){cells.forEach(c=>{const el=$(`#board [data-x="${c.x}"][data-y="${c.y}"]`); if(el)el.classList.add('pop')})}
function drop(){for(let x=0;x<8;x++){const col=[]; for(let y=7;y>=0;y--)if(board[y][x])col.push(board[y][x]); for(let y=7;y>=0;y--)board[y][x]=col[7-y]||{type:rand(),special:null,dir:Math.random()<.5?'row':'col',new:true}}}
function specialCells(c,target){const p=board[c.y][c.x]; const cells=[]; if(!p)return cells; if(p.special==='rocket'){if(p.dir==='col'){for(let y=0;y<8;y++)cells.push({x:c.x,y})}else{for(let x=0;x<8;x++)cells.push({x,y:c.y})} beam(p.dir,c)} else if(p.special==='bomb'){for(let y=c.y-2;y<=c.y+2;y++)for(let x=c.x-2;x<=c.x+2;x++)if(x>=0&&x<8&&y>=0&&y<8)cells.push({x,y}); shake()} else if(p.special==='rainbow'){const t=target||p.type; for(let y=0;y<8;y++)for(let x=0;x<8;x++)if(board[y][x].type===t)cells.push({x,y}); flash()} return cells}
function activate(c,target,label){const cells=specialCells(c,target); if(!cells.length){busy=false; return} board[c.y][c.x].special=null; moves=Math.max(0,moves); resolve([cells],{label:label||'Power!'})}
function useBooster(name){if(screen!=='game')show('game'); if(busy){hint('Wait for the board to settle.');return} if(name==='moves'){if(boosters.moves<=0){hint('No Moves +5 left');return} boosters.moves--; moves+=5; updateGame(); toast('+5 MOVES'); tone(860,.12); return} if(boosters[name]<=0){hint('No '+name+' left');return} boosters[name]--; const c=selected||suggestTarget(name); const btn=document.querySelector(`[data-boost="${name}"]`); if(btn){btn.classList.remove('used'); void btn.offsetWidth; btn.classList.add('used')} let cells=[]; if(name==='rocket'){for(let x=0;x<8;x++)cells.push({x,y:c.y}); beam('row',c); toast('ROCKET!')} if(name==='bomb'){for(let y=c.y-2;y<=c.y+2;y++)for(let x=c.x-2;x<=c.x+2;x++)if(x>=0&&x<8&&y>=0&&y<8)cells.push({x,y}); shake(); toast('BOOM!')} if(name==='rainbow'){const t=board[c.y][c.x].type; for(let y=0;y<8;y++)for(let x=0;x<8;x++)if(board[y][x].type===t)cells.push({x,y}); flash(); toast('RAINBOW!')} moves=Math.max(0,moves-1); updateGame(); resolve([cells],{label:"Coco's Treat!"}); if(!state.tutorial.boost){state.tutorial.boost=true; save();}}
function suggestTarget(name){let best={x:3,y:3},score=-1; for(let y=0;y<8;y++)for(let x=0;x<8;x++){let p=board[y][x],v=goals.some(g=>g.type===p.type)?4:1; if(name==='bomb')v+=Math.max(0,4-Math.abs(x-3)-Math.abs(y-3)); if(v>score){score=v;best={x,y}}} return best}
function checkEnd(){updateGame(); if(goals.every(g=>g.got>=g.need)){state.coins+=100; state.stars++; const bonus=state.level%3===0?'rainbow':state.level%2===0?'bomb':'rocket'; boosters[bonus]=(boosters[bonus]||0)+1; state.level++; save(); sync(); fanfare(); showModal(`<h2>Level Complete!</h2><div class="starsBig">★★★</div><p>+100 coins, +1 room star, +1 ${bonus}</p><button class="btn green" onclick="closeModal();show('makeover')">Decorate Room</button><br><br><button class="btn blueBtn" onclick="closeModal();startLevel()">Next Level</button>`)} else if(moves<=0){showModal('<h2>Out of Moves!</h2><div class="starsBig">+5</div><p>Use five extra moves and keep helping Coco.</p><button class="btn green" id="extraMoves">Use 900 coins</button><br><br><button class="btn blueBtn" onclick="closeModal();show(\'lobby\')">Lobby</button>'); setTimeout(()=>{$('#extraMoves').onclick=()=>{moves+=5; updateGame(); closeModal()}},20)}}
function showModal(html){$('#modalContent').innerHTML=html; $('#modal').classList.add('show')}
function closeModal(){ $('#modal').classList.remove('show') }
function coachIntro(){state.tutorial.intro=true; save(); showModal('<h2>How to play</h2><p>Swap pieces to match 3. The goals on the left are the exact pieces you need to collect.</p><p><b>Match 4</b> makes a rocket. <b>Match 5</b> makes a rainbow treat.</p><button class="btn green" onclick="closeModal()">Got it</button>')}
function coachPower(type){showModal(`<h2>${type==='rainbow'?'Rainbow Treat':type==='bomb'?'Bomb Piece':'Rocket Piece'}</h2><p>Tap this special piece on the board to fire it. Special pieces do not need another match.</p><button class="btn green" onclick="closeModal()">Cute</button>`) }
function coachRoom(){if(state.tutorial.room)return; state.tutorial.room=true; save(); hint('Spend stars here to make Coco’s cafe room nicer.');}
function renderRoom(){['sofa','table','plant','curtain'].forEach(k=>{const el=$('.'+k); if(el)el.classList.toggle('roomDone',!!state.room[k])}); const after=$('.roomSide.after'); if(after&&!$('.roomTaskHud')){const d=document.createElement('div'); d.className='roomTaskHud'; after.appendChild(d)} const hud=$('.roomTaskHud'); if(hud){const next=ROOM_TASKS.find(t=>!state.room[t.key]); hud.innerHTML=next?`<b>Next task</b><br>${next.label}<br><small>Cost: 1 star</small>`:'<b>Room complete!</b><br>Coco loves it.'}}
function doRoomTask(){const next=ROOM_TASKS.find(t=>!state.room[t.key]); if(!next){showModal('<h2>Room Complete!</h2><p>Coco’s cafe corner is already looking gorgeous.</p><button class="btn green" onclick="closeModal()">Nice</button>');return} if(state.stars<=0){showModal('<h2>Need a Star</h2><p>Win one level to earn a room star.</p><button class="btn green" onclick="closeModal();show(\'game\')">Play Level</button>');return} state.stars--; state.room[next.key]=true; save(); sync(); renderRoom(); melody(); showModal(`<h2>Room Updated!</h2><div class="starsBig">★</div><p>${next.reward}</p><button class="btn green" onclick="closeModal()">Love it</button>`)}
function popup(kind){ if(kind==='settings')showModal('<h2>Settings</h2><p>Sound and vibration for Coco.</p><button class="btn green" id="soundToggle">Sound '+(state.sound?'On':'Off')+'</button><br><br><button class="btn blueBtn" id="vibeToggle">Vibration '+(state.vibe?'On':'Off')+'</button>'); if(kind==='pause')showModal('<h2>Paused</h2><p>Coco is having a tiny treat break.</p><button class="btn green" onclick="closeModal()">Resume</button><br><br><button class="btn blueBtn" onclick="startLevel()">Restart</button><br><br><button class="btn goldBtn" onclick="closeModal();show(\'lobby\')">Lobby</button>'); if(kind==='daily')showModal('<h2>Daily Bonus</h2><div class="starsBig">★</div><p>Claim 250 coins for Coco.</p><button class="btn green" id="dailyClaim">Claim</button>'); if(kind==='reno')doRoomTask(); if(kind==='claim')showModal('<h2>Claimed!</h2><div class="starsBig">+250</div><p>Reward added.</p><button class="btn green" onclick="closeModal()">Continue</button>'); if(['pig','spin','chest'].includes(kind))showModal('<h2>'+({pig:'Piggy Bank',spin:'Daily Spin',chest:'Star Chest'}[kind])+'</h2><p>Play levels to fill this reward.</p><button class="btn green" onclick="closeModal()">Nice</button>'); setTimeout(()=>{const s=$('#soundToggle'); if(s)s.onclick=()=>{state.sound=!state.sound; save(); popup('settings')}; const v=$('#vibeToggle'); if(v)v.onclick=()=>{state.vibe=!state.vibe; save(); popup('settings')}; const d=$('#dailyClaim'); if(d)d.onclick=()=>{state.coins+=250; save(); sync(); popup('claim')}},20); tone(650,.08)}
function toast(txt){const frame=$('#game .frame'); if(!frame)return; const e=document.createElement('div'); e.className='toast'; e.textContent=txt; frame.appendChild(e); setTimeout(()=>e.remove(),1200)}
function hint(txt){const frame=$('#game .frame'); if(!frame)return; const e=document.createElement('div'); e.className='hint'; e.textContent=txt; frame.appendChild(e); setTimeout(()=>e.remove(),1800)}
function particles(cells){const frame=$('#game .frame'),be=$('#board'); if(!frame||!be)return; const br=be.getBoundingClientRect(),fr=frame.getBoundingClientRect(),s=br.width/8; cells.slice(0,22).forEach(c=>{for(let i=0;i<4;i++){const p=document.createElement('i'); p.className='boomBit'; p.style.left=(br.left-fr.left+c.x*s+s/2)+'px'; p.style.top=(br.top-fr.top+c.y*s+s/2)+'px'; p.style.setProperty('--dx',(Math.random()*120-60)+'px'); p.style.setProperty('--dy',(Math.random()*110-85)+'px'); frame.appendChild(p); setTimeout(()=>p.remove(),800)}})}
function beam(dir,c){const frame=$('#game .frame'),b=$('#board'); if(!frame||!b)return; const br=b.getBoundingClientRect(),fr=frame.getBoundingClientRect(),s=br.width/8,el=document.createElement('div'); el.className='beam'; if(dir==='col'){el.style.width='18px';el.style.height=br.height+'px';el.style.left=(br.left-fr.left+c.x*s+s/2-9)+'px';el.style.top=(br.top-fr.top)+'px'}else{el.style.width=br.width+'px';el.style.height='18px';el.style.left=(br.left-fr.left)+'px';el.style.top=(br.top-fr.top+c.y*s+s/2-9)+'px'} frame.appendChild(el); setTimeout(()=>el.remove(),420)}
function shake(){const b=$('#board'); if(!b)return; b.classList.remove('shake'); void b.offsetWidth; b.classList.add('shake')}
function flash(){const f=$('#flash'); if(!f)return; f.classList.remove('on'); void f.offsetWidth; f.classList.add('on')}
function shockwave(){const frame=$('#game .frame'); if(!frame)return; const e=document.createElement('div'); e.className='shockwave'; frame.appendChild(e); setTimeout(()=>e.remove(),700)}
function bind(){document.addEventListener('pointerdown',ctx,{once:true}); document.addEventListener('click',e=>{const b=e.target.closest('button'); if(!b)return; ctx(); if(b.dataset.screen)show(b.dataset.screen); if(b.dataset.popup)popup(b.dataset.popup); if(b.dataset.boost)useBooster(b.dataset.boost); if(b.dataset.claim){state.coins+=250; state.inbox=true; save(); sync(); popup('claim')} if(b.id==='closeModal')closeModal()}); $('#startSound').onclick=()=>{ctx(); melody(); $('#soundGate').remove()}; const be=$('#board'); be.addEventListener('pointerdown',e=>{e.preventDefault(); if(busy)return; const c=cellAt(e.clientX,e.clientY); if(!c)return; const p=board[c.y][c.x]; if(p.special){moves=Math.max(0,moves-1); activate(c,null,'Power!'); return} if(selected&&adjacent(selected,c)){const a=selected; selected=null; attemptSwap(a,c); return} selected=c; down={id:e.pointerId,c}; try{be.setPointerCapture(e.pointerId)}catch(err){} render(); tone(520,.04)}); be.addEventListener('pointermove',e=>{if(!down||busy)return; e.preventDefault(); const c=cellAt(e.clientX,e.clientY); if(adjacent(down.c,c)){const a=down.c; down=null; selected=null; attemptSwap(a,c)}}); be.addEventListener('pointerup',e=>{e.preventDefault(); down=null});}
window.show=show; window.closeModal=closeModal; window.startLevel=()=>{closeModal();newLevel()}; window.__gameTest={state,boosters,get board(){return board},show,newLevel,useBooster,attemptSwap,groups:getGroups};
bind(); newLevel(); sync(); setTimeout(()=>{$('#loading').classList.add('hide'); show('home')},450);
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').then(r=>r.update()).catch(()=>{})}
})();
